### PR TITLE
Fix rate limit interval

### LINKED ISSUE #192: Fix rate limit interval issue
Currently, once you get the 429 error after hitting the rate limit, you are blocked for the amount of time that has been specified (eg. once you hit a rate limit that's set to 10 per minute, you will be blocked for 1 minute afterwards). This should be modified so that you are blocked for the average time interval (eg. 60/10 = 6 seconds). (See [Leaky bucket algorithm](https://en.wikipedia.org/wiki/Leaky_bucket))

### PR DESCRIPTION
**Pull request by alexsong93**
Fixes #192 @codymwalker @mhamann PTAL

### CODE REVIEW

File: scripts/lua/policies/rateLimit.lua [hunk 1]
```diff
@@ -19,56 +19,41 @@
...
 local REDIS_PASS = os.getenv("REDIS_PASS")
-local req = require "lib/resty/limit/req"
 local utils = require "lib/utils"
-local logger = require "lib/logger"
 local request = require "lib/request"
 local redis = require "lib/redis"
 
 local _M = {}
 
---- Limit a resource/api/tenant, based on the passed in rateLimit object
```
Comment (mhamann) [inline scripts/lua/policies/rateLimit.lua]: Seems like this is a useful comment. Any reason to remove it?

File: scripts/lua/policies/rateLimit.lua [hunk 2]
```diff
@@ -19,56 +19,41 @@
...
-    rate = r,
-    interval = obj.interval,
-    log_level = ngx.NOTICE,
-    rds = {host = REDIS_HOST, port = REDIS_PORT, pass = REDIS_PASS}
-  }
-  local ok = req.limit(config)
-  if not ok then
-    logger.err('Rate limit exceeded. Sending 429')
-    request.err(429, 'Rate limit exceeded.')
+  local red = redis.init(REDIS_HOST, REDIS_PORT, REDIS_PASS, 10000)
```
Comment (mhamann) [inline scripts/lua/policies/rateLimit.lua]: I think @taylorking found that this call can significantly add to the time it takes to process a request. We should already have an initialized redis connection available at this point, so is there a need to init another one?

File: scripts/lua/management/lib/swagger.lua [hunk 3]
```diff
@@ -98,23 +98,24 @@ end
 function parseRateLimit(swagger, policies)
   local rlObj = swagger["x-gateway-rate-limit"]
   rlObj = (rlObj == nil) and swagger["x-ibm-rate-limit"] or rlObj
+  local unit
```
Comment (mhamann) [inline scripts/lua/management/lib/swagger.lua]: What does making this a local variable buy us? How is it better than it was before?

File: scripts/lua/policies/rateLimit.lua (hunk 2 above)
Comment (taylorking) [inline scripts/lua/policies/rateLimit.lua]: The short term solution here might be to make it limitWithRedis(red, obj, apiKey).. Will also make it unit testable as well potentially

Comment (taylorking) [inline scripts/lua/policies/rateLimit.lua]: The short term solution here might be to make it limitWithRedis(red, obj, apiKey).. Will also make it unit testable

File: scripts/lua/management/lib/swagger.lua (hunk 3 above)
Comment (taylorking) [inline scripts/lua/management/lib/swagger.lua]: Are you building swagger processing into the apigateway?

File: scripts/lua/management/lib/swagger.lua [hunk 4]
```diff
@@ -98,23 +98,24 @@ end
...
+      unit = 86400
     else
-      rlObj.unit = 60   -- default to minute
+      unit = 60   -- default to minute
     end
     policies[#policies+1] = {
       type = "rateLimit",
       value = {
-        interval = rlObj.unit * rlObj.units,
+        interval = unit * rlObj.units,
```
Comment (taylorking) [inline scripts/lua/management/lib/swagger.lua]: :+1:

File: scripts/lua/management/lib/swagger.lua (hunk 3 above)
Comment (alexsong93) [inline scripts/lua/management/lib/swagger.lua]: Previously, it was modifying the swagger file directly, resulting in the modified swagger being stored and being returned to the user. By making this a local variable, it keeps the original swagger with `minute`, `second`, etc. instead of it being modified to `60`, `1`, etc.

File: scripts/lua/policies/rateLimit.lua (hunk 1 above)
Comment (alexsong93) [inline scripts/lua/policies/rateLimit.lua]: Added the comments back in there

File: scripts/lua/policies/rateLimit.lua (hunk 2 above)
Comment (alexsong93) [inline scripts/lua/policies/rateLimit.lua]: Modified to reuse an existing redis connection
