### PR TITLE
Fix cors in v2 management interface

### LINKED ISSUE #186: GET of API with enabled CORS returns 'null' instead of 'true'
1. Use the API GW management I/F to create (POST) an API with CORS enabled
2. Observe the following CORS setting in the POST response
```
     cors:
         enabled: true
```
3. GET the same API via API GW management IF (GET on the /api/SPACEGUID/BASEPATH endpoint)
4. The returned JSON has
```
...
"cors": {
    "enabled": null
}
...
```

Also, when an API is created via the CLI and CORS is not enabled, the returned API from GET does not have the CORS field at all.

### PR DESCRIPTION
**Pull request by alexsong93**
Fixes #186 @mhamann PTAL

### CODE REVIEW

File: tests/scripts/lua/management/lib/swagger.lua [hunk 1]
```diff
@@ -31,6 +31,9 @@ describe('Testing v2 management interface', function()
         "name": "Hello World API",
         "resources": {
           "/hello": {
+            "cors": {
+              "origin": "true"
```
Comment (mdeuser) [inline tests/scripts/lua/management/lib/swagger.lua]: @alexsong93 - is the value cors.enabled or cors.origin ?  in other swagger files, i thought i saw cors.enabled.

Comment (alexsong93) [inline tests/scripts/lua/management/lib/swagger.lua]: @mdeuser if you're using the v2 interface, you should set `cors.enabled` in the `x-gateway-configuration` block:
```
"x-gateway-configuration": {
  "cors": {
     "enabled": true
   },
   ...
}
```
What you're seeing is how the Swagger doc is converted behind the scenes to what the gateway understands (and also how it is handled in the v1 interface).

I have a PR open for the v2 interface docs which should clear things up more: https://github.com/openwhisk/openwhisk-apigateway/pull/190
